### ISSUE TITLE
Add permanent step assist as an option

### ISSUE THREAD

**Issue by C0rn3j** [blay09/ClientTweaks#11]
Would you consider ADDING permanent step assist to the mod, since your mod already touches on step assist?

I hate the MC movement and step assist mods fix that, but this mod hasn't been updated in a while.

https://minecraft.curseforge.com/projects/uphill-step-assist

**Comment by BlayTheNinth** [comment]
Even though it's possible to allow client-side step-assist, that's only possible because the server does not care enough to check if it's actually allowed. It has also become a feature locked behind items in a bunch of mods. 

Adding it to this mod would mean changing gameplay in a manner visible to other players, as opposed to just being convenience / fixes. I want to keep this one as client-ish as possible, and I feel this feature crosses the line and should be kept separate. Also thinking of PVP servers that allow certain client-side mods as long as they don't grant an unfair advantage.
