### ISSUE TITLE
Potion Effects still show, despite being disabled in the config.

### ISSUE THREAD

**Issue by katubug** [blay09/ClientTweaks#24]
Hi! Firstly, thanks for the excellent mod, I use it all the time! :D

Secondly, I'm having an issue where my potion effects (the little rising swirlies) are still showing in first and third person even with my config set to:

``` # This option will hide your own potion particle effects for your client (other players will still see them). [default: false]
    B:"Hide Own Particle Effects"=true
```

Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2838-universal
ClientTweaks: ClientTweaks_1.12.2-3.1.11.jar

Here is a link to my full modlist with versions: https://pastebin.com/ysH7wRa4

Let me know if you need any other information from me. Thank you for your time!

**Comment by ZeekDaGeek** [comment]
About 4 months ago RandomPatches added a fix for [MC-10369](https://bugs.mojang.com/browse/MC-10369) which makes particles spawned on the server side not show up on the client side.

Summary:
```
Many of Minecraft's particles aren't shown due to two long-standing bugs:
- MC-10369 - server-sided particle spawning doesn't spawn particles for clients (fixed in Minecraft 1.14)
- MC-93826 - Breeding hearts show only once instead of all the time an animal can breed
Lots of particles will appear once again that haven't done so in the vanilla game since Minecraft 1.3 from July 2012.
These particles include:
- Heart particles constantly popping up from animals in love
- Small snow particles upon building a snow golem
- Snowball particles when an iron golem or wither boss is built
- Large smoke particles when lava and water mix
- Red particles on redstone torch burn out
- Armor breaking particles when worn by a mob
- Smoke when placing an eye of ender in an end portal frame
- A heap of heart particles around one of the parents when a baby animal is born
- Explosion particles when the ender dragon destroys blocks upon touching them
- These fixes work on Minecraft 1.10 and newer and are server-sided.
- These fixes were originally written by Fuzs_, who asked me to implement Particle Fixes into RandomPatches. You can view his screenshots here.
- This feature will disable itself if Particle Fixes is installed.
```

I'm not sure who's to blame for this feature not working:
- Either the way RandomPatches implements the feature doesn't allow for particles to be canceled OR
- Client Tweaks and every other "No Client Particles" config option (because there are a few of them) need to disable server side particles?

cc: RandomPatches developers: @TheRandomLabs
Maybe they RandomLabs knows more about this?


### Temporary Fix
RandomPatches' "Particle Fixes" needs to be disabled **on the server side** to allow for Client Tweaks to do this at the moment.

**Comment by katubug** [comment]
Thank you very much for that! I'll use the workaround for now, and hopefully it will be resolved in the future. :)

**Comment by BlayTheNinth** [comment]
https://github.com/TheRandomLabs/RandomPatches/issues/47
